#!/bin/bash
############################################
#                                          #
#   Script That Automate The Installation  #
#       Of Tonics Apps and                 #
#         Various Packages                 #
#                                          #
#   Author: The_Devsrealm_Guy              #
#   Website: https://devsrealm.com         #
#   Last Edited: May 2021                  #
#                                          #
############################################

PHP_VERSION=8.1
logfile=errorlog.txt

#
# Check if user have the proper have privileges
#

if [ "$(id -u)" -ne 0 ]; then
  echo -e "Please Run This Program as a Root user only" >&2
  exit 1
fi

#######################################
#   WE CREATE ALL THE FUNCTIONS HERE  #
#######################################

source func/reusable_functions.sh
source mainbackup.sh
source mariadb/installMariadb.sh
source mailserver/opendkim/opendkimInstall.sh
source mailserver/installMailServer.sh
source nginx/installNginx.sh
source sftp/installSftp.sh
source php/installPhp.sh
source certbot/installCertbot.sh
source standalone/dns.sh

#####################################
#   WE START THE MAIN CODE HERE ;)  #
#####################################

#
#   This checks if one and only arguments is passed
#   "$#" contains the number of command line arguments.
#   The "$0" is the parameter that comes before other parameters, so, we can say...
#   "$0" is the name of the  script (complete path as
#   typed in on the command line (e.g. "/home/mark/menu")
#
[ $# == 1 ] || usage "$0" websitename.com # exits the program
echo
site_available="/etc/nginx/sites-available"
site_enabled="/etc/nginx/sites-enabled"

sudo apt-get -y install boxes 2>>${logfile} >/dev/null &
spinner
